### ISSUE TITLE
Uploading large networks

### ISSUE THREAD

**Issue by SantosRAC** [sepro/CoNekT#10]
Dear @sepro,

Greetings from Brazil!

I am trying to upload a large network for a species (could successfully upload smaller networks in other species).

Even after changing the `mkdtemp` in Flask `config.py` (`TMP_DIR`) and `mkstemp` in `add_coexpression_network()` (`expression_network.py`), both pointing to a hard disk with a lot of free space, I still get into `No space left on device`.

Our MySQL/MariaDB is configured to store in this large disk and it looks like the problem happens during import, before I really start doing anything with the imported network. Have you experienced similar problems?

Here is where error is raised:

```bash
werkzeug[11648] INFO 127.0.0.1 - - [27/Aug/2022 19:34:11] "POST /admin_controls/add/coexpression_network HTTP/1.1" 500 -
2022-08-27 19:34:11 user werkzeug[11648] ERROR Error on request
```

All the best.

**Comment by sepro** [comment]
All instances of mkstemp should have ```dir=current_app.config['TMP_DIR']``` as a parameter so they respect the settings in the config file. This isn't the case for the uploads from the admin panel. Thanks for pointing that out! That definitely is an issue on its own.

To pinpoint where this issue is I need a few details. Could you enable DEBUG mode and SQLALCHEMY_ECHO (in the config), retry and post the stacktrace (should appear in the browser when the issue is raised)? Then check the command line if any SQL queries were actually executed.

How large is the file that is causing an issue ?

Note that even if there is sufficient space on the disk, this might be a permission or quota issue.

**Comment by SantosRAC** [comment]
Hi @sepro ,

The size of file I am trying to upload is 2.4Gb.

Here is the stacktrace:

```
2022-08-29 23:32:06 LabBCESVM001 werkzeug[25350] INFO 127.0.0.1 - - [29/Aug/2022 23:32:06] "POST /admin_controls/add/coexpression_network HTTP/1.1" 500 -
2022-08-29 23:32:06 LabBCESVM001 werkzeug[25350] ERROR Error on request:
Traceback (most recent call last):
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask_wtf/csrf.py", line 221, in csrf_protect
    self.protect()
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask_wtf/csrf.py", line 249, in protect
    validate_csrf(self._get_csrf_token())
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask_wtf/csrf.py", line 229, in _get_csrf_token
    for key in request.form:
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/utils.py", line 91, in __get__
    value = self.func(obj)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 479, in form
    self._load_form_data()
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/flask/wrappers.py", line 168, in _load_form_data
    RequestBase._load_form_data(self)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 318, in _load_form_data
    self._get_stream_for_parsing(), mimetype, content_length, options
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/formparser.py", line 231, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/formparser.py", line 130, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/formparser.py", line 252, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/formparser.py", line 583, in parse
    return self.cls(form), self.cls(files)
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/datastructures.py", line 419, in __init__
    for key, value in mapping or ():
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/formparser.py", line 581, in <genexpr>
    form = (p[1] for p in formstream if p[0] == "form")
  File "/data2/CoNekT-Bioenergy/conekt_bioenergyapp/CoNekT/lib/python3.6/site-packages/werkzeug/formparser.py", line 554, in parse_parts
    _write(ell)
  File "/usr/lib/python3.6/tempfile.py", line 907, in write
    rv = file.write(s)
OSError: [Errno 28] No space left on device
```

Browser returns:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Thanks a lot,
Renato Santos.

**Comment by sepro** [comment]
There are no lines in the stacktrace pointing to a line in CoNekT's code, so this suggests a limit of a third party library or the uwsgi server is the bottleneck here. That will not be an easy fix, certainly this will require more time than I can currently commit.

So the pragmatic solution is to prune the network prior to uploading the data.

**Comment by SantosRAC** [comment]
Thanks a lot, @sepro !
